apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-config
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  RESOURCEPROVIDERAPI_EVENTS_NATS_URL: "{{ .Values.api.events.nats.url }}"
  RESOURCEPROVIDERAPI_EVENTS_NATS_PUBLISHPREFIX: "{{ .Values.api.events.nats.publishPrefix }}"
  RESOURCEPROVIDERAPI_EVENTS_NATS_QUEUEGROUP: "{{ .Values.api.events.nats.queueGroup }}"
  RESOURCEPROVIDERAPI_EVENTS_NATS_SOURCE: "{{ .Values.api.events.nats.source }}"
  RESOURCEPROVIDERAPI_EVENTS_NATS_CONNECTTIMEOUT: "{{ .Values.api.events.nats.connectTimeout }}"
  RESOURCEPROVIDERAPI_EVENTS_NATS_SHUTDOWNTIMEOUT: "{{ .Values.api.events.nats.shutdownTimeout }}"
{{- if .Values.api.events.nats.credsSecretName }}
  RESOURCEPROVIDERAPI_EVENTS_NATS_CREDSFILE: "{{ .Values.api.events.nats.credsFile }}"
{{- end }}
  RESOURCEPROVIDERAPI_OIDC_ENABLED: "{{ .Values.api.oidc.enabled }}"
  RESOURCEPROVIDERAPI_OIDC_AUDIENCE: "{{ .Values.api.oidc.audience }}"
  RESOURCEPROVIDERAPI_OIDC_ISSUER: "{{ .Values.api.oidc.issuer }}"
  RESOURCEPROVIDERAPI_OIDC_JWKS_REMOTE_TIMEOUT: "{{ .Values.api.oidc.jwksRemoteTimeout }}"
  RESOURCEPROVIDERAPI_SERVER_LISTEN: ":{{ .Values.api.listenPort }}"
  RESOURCEPROVIDERAPI_SERVER_SHUTDOWN_GRACE_PERIOD: "{{ .Values.api.shutdownGracePeriod }}"
  RESOURCEPROVIDERAPI_PERMISSIONS_URL: "{{ .Values.api.permissions.url }}"
{{- if .Values.api.tracing.enabled }}
  RESOURCEPROVIDERAPI_TRACING_ENABLED: "{{ .Values.api.tracing.enabled }}"
  RESOURCEPROVIDERAPI_TRACING_PROVIDER: "{{ .Values.api.tracing.provider }}"
  RESOURCEPROVIDERAPI_TRACING_ENVIRONMENT: "{{ .Values.api.tracing.environment }}"
{{- if eq .Values.api.tracing.provider "jaeger" }}
  RESOURCEPROVIDERAPI_TRACING_JAEGER_ENDPOINT: "{{ .Values.api.tracing.jaeger.endpoint }}"
  RESOURCEPROVIDERAPI_TRACING_JAEGER_USER: "{{ .Values.api.tracing.jaeger.user }}"
  RESOURCEPROVIDERAPI_TRACING_JAEGER_PASSWORD: "{{ .Values.api.tracing.jaeger.password }}"
{{- end }}
{{- if eq .Values.api.tracing.provider "otlpgrpc" }}
  RESOURCEPROVIDERAPI_TRACING_OTLP_ENDPOINT: "{{ .Values.api.tracing.otlp.endpoint }}"
  RESOURCEPROVIDERAPI_TRACING_OTLP_INSECURE: "{{ .Values.api.tracing.otlp.insecure }}"
  RESOURCEPROVIDERAPI_TRACING_OTLP_CERTIFICATE: "{{ .Values.api.tracing.otlp.certificate }}"
{{- end }}
{{- end }}
{{- with .Values.api.trustedProxies }}
  RESOURCEPROVIDERAPI_SERVER_TRUSTED_PROXIES: "{{ join " " . }}"
{{- end }}
