---
name: Test - Golang

# Run for all pushes to main and pull requests when Go or YAML files change
on:
  push:
  pull_request:

jobs:
  gotest:
    name: test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ci-database:
          [
            "sqlite"
          ]
        include:
          - ci-database: "sqlite"
            env-database-uri: "sqlite://file:ent?mode=memory&cache=shared&_fk=1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Run go tests for sqlite
        run: RESOURCEPROVIDERAPI_TESTDB_URI="sqlite://file:ent?mode=memory&cache=shared&_fk=1" go test -race -coverprofile=coverage.txt -covermode=atomic -tags testtools ./...